### ISSUE TITLE
"nix build" results in "ModuleNotFoundError: No module named 'poetry'"

### ISSUE THREAD

**Issue by svenkeidel** [runtimeverification/imp-semantics#5]
Hi, thanks for the hard work.

Steps to reproduce:
```
$ git clone https://github.com/runtimeverification/imp-semantics
$ cd imp-semantics/kimp
$ nix build
```

Output while building `pyk`:
```
ModuleNotFoundError: No module named 'poetry'
```

Nix version: 2.15.1
Flake.lock: [flake.lock.txt](https://github.com/runtimeverification/imp-semantics/files/11784368/flake.lock.txt)

**Comment by geo2a** [comment]
Thanks for your interest @svenkeidel! 

We've updated the installation instructions, please have a look into `README.md`.

I've removed the Nix flake for now, but it will likely be re-introduced later.
